service: '3.2'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin@1997'
      MYSQL_DATABASE: 'project'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Admin@1997'
    adminer:
      image:adminer
      restart: always
      ports:
        -8888:8080
